# Service Name
spring:
  application:
    name: order-service


# Profiles
---
spring:
  profiles:
    active: dev


# Spring Cloud Config Server URI
---
spring:
  config:
    import: "configserver:"

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true