# DB Details
---
spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=users_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: 12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
spring:
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true

