# Service Port Number
server:
  port: 9200

# Service Name
spring:
  application:
    name: payment-service


# DB Details
---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true