pipeline {
    agent any
    stages {
        stage("Build") {
             steps {
                echo ">>>>> Build Service Registry..."
                mvn clean install
             }
        }
    }
}