pipeline {
    agent any
    stages {
        stage('Build') {
             steps {
                    echo ">>>>> Build Service Registry..."
                    sh 'pwd'
                    sh 'rm -r ./service-registry'
                    sh 'cd ./restaurant-system/microservices/service-registry/'
                    sh 'mvn clean install'
             }
        }
    }
}