# Service Port Number
server:
  port: 9100

# Service Registry
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

# DB Details
---
spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=order_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: 12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
