# Service Name
spring:
  application:
    name: order-service

# Profiles
---
spring:
  profiles:
    active: dev


# Spring Cloud Config Server URI
---
spring:
  config:
    import: "configserver:"
#  cloud:
#    config:
#      import-check:
#        enabled: false
