# Service Name
spring:
  application:
    name: payment-service

# Profiles
---
spring:
  profiles:
    active: dev


# Spring Cloud Config Server URI
---
spring:
  config:
    import: "configserver:"
